import Head from "next/head";
import { Dashboard } from "./Components/Dashboard/Dashboard";

const Home = () => {
  return (
    <div>
      <Head>
        <title>SubsPay</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className="h-screen">
        <Dashboard />
      </main>
    </div>
  );
};

export default Home;
